import Head from "next/head";
import Link from "next/link";
import { useState, useEffect } from "react";


import Navbar from "../../components/Navbar";

export default function Admin() {

    const [title, setTitle] = useState("");
    const [description, setDescription] = useState("");
    const [resolverUrl, setResolverUrl] = useState("");
    const [timestamp, setTimestamp]= useState(Date());

    return (
        <>
            <div className="flex flex-col justify-center items-center h-full p-5">
                <Head>
                    <title>Prediction World</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <Navbar />
                <main className="w-full flex flex-col py-4 max-w-5xl pb-6">
                    <Link href="/admin/markets" className="mt-5 rounded-lg py-3 text-center w-full bg-blue-700 text-white font-bold mb-5">
                        See All Markets
                    </Link>
                    <div className="w-full flex flex-col pt-1 border border-gray-300 p-5 rounded-lg ">
                        <span className="text-lg font-semibold mt-4">Add New Market</span>
                        <span className="text-lg font mt-6 mb-1">Market Title</span>
                        <input
                            type="input"
                            name="title"
                            value={title}
                            onChange={(e) => setTitle(e.target.value)}
                            className="w-full py-3 px-3 text-base text-gray-700 bg-gray-100 rounded-md focus:outline-none"
                            placeholder="Title"
                            autoComplete="off"
                        />
                        <span className="text-lg font mt-6 mb-1">Market Description</span>
                        <textarea
                            name="description"
                            value={description}
                            onChange={(e) => setDescription(e.target.value)}
                            className="w-full py-3 px-3 text-base text-gray-700 bg-gray-100 rounded-md focus:outline-none"
                            placeholder="Description"
                            autoComplete="off"
                        >
                        </textarea>
                        <span className="text-lg font mt-6 mb-1">Resolve URL</span>
                        <input
                            type="input"
                            name="resolverUrl"
                            value={resolverUrl}
                            onChange={(e) => setResolverUrl(e.target.value)}
                            className="w-full py-3 px-3 text-base text-gray-700 bg-gray-100 rounded-md focus:outline-none"
                            placeholder="URL"
                            autoComplete="off"
                        />
                        <span className="text-lg font mt-6 mb-1">End Date</span>
                        <input
                            type="date"
                            name="timestamp"
                            // value={timestamp}
                            onChange={(e) => {
                                setTimestamp(e.target.valueAsDate?.getTime());
                            }}
                            className="w-full py-3 px-3 text-base text-gray-700 bg-gray-100 rounded-md focus:outline-none"
                            autoComplete="off"
                        />
                    </div>
                </main>
            </div>
        </>
    );
}