import Head from "next/head";
import Link from "next/link";

import Navbar from "../../components/Navbar";

export default function Admin() {
    return (
        <>
            <div className="flex flex-col justify-center items-center h-full p-5">
                <Head>
                    <title>Prediction World</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <Navbar />
                <main className="w-full flex flex-col py-4 max-w-5xl pb-6">
                    <Link href="/admin/markets" className="mt-5 rounded-lg py-3 text-center w-full bg-blue-700 text-white font-bold mb-5">
                        See All Markets
                    </Link>
                    <div className="w-full flex flex-col pt-1 border border-gray-300 p-5 rounded-lg ">
                        <span className="text-lg font-semibold mt-4">Add New Market</span>
                    </div>
                </main>
            </div>
        </>
    );
}