import Head from "next/head";
import Img from "next/image";
import { useState } from "react";

import Navbar from "../../components/Navbar";


export default function Detail() {
    const [market, setMarket] = useState({
        title: "title of market"
    });

    return(
        <div className="flex flex-col justify-center items-center h-full">
            <Head>
                <title>Prediction World</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <main className="w-full flex flex-col sm:flex-row py-4 max-w-5xl">
                <div className="w-full flex flex-col pt-1">
                    <div className="p-6 rounded-lg flex flex-row justify-start border border-gray-300">
                        <div className="flex flex-row">
                            <div className="h-w-15 pr-4">
                                <Img
                                    src="/placeholder.jpg"
                                    className="rounded-full"
                                    width={55}
                                    height={55}
                                />
                            </div>
                            <div className="flex flex-col justify-start w-1/2 space-y-1">
                                <span className="text-xs font-light text-gray-500 whitespace-nowrap">
                                    Some placeholder
                                </span>
                                <span className="text-lg font-semibold whitespace-nowrap">
                                    {market?.title}
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </div>
    );
}