import { MENU_TYPE } from "@/constants/Constant";
import "tailwindcss/tailwind.css";
import "../styles/globals.css";

import { LoadingContext } from "@/contexts/LoadingContext";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { useMenuStore } from "../store/useMenuStore";

export default function App({ Component, pageProps }) {
    const router = useRouter();
    const { menu, marketid } = router.query;
    const { setCurrentMenu, setCurrentMarketID } = useMenuStore();
    const defaultMenu = menu && menu != "" ? menu : MENU_TYPE.MARKET;
    const defaultMarketID = marketid ? marketid : null;

    //Loading Context
    const [isPageLoading, setIsPageLoading] = useState(false);
    const [isMarketLoading, setIsMarketLoading] = useState(false);

    useEffect(() => {
        setCurrentMenu(defaultMenu);
        setCurrentMarketID(defaultMarketID);
    }, [menu, marketid]);

    return (
        <LoadingContext.Provider value={{ isPageLoading, setIsPageLoading, isMarketLoading, setIsMarketLoading }}>
            <Head>
                <title>Saba Orb</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/logo.ico" />
            </Head>
            <Component {...pageProps} />
        </LoadingContext.Provider>
    );
}
