import Head from "next/head";
import { useState, useEffect } from "react";
import { ethers } from "ethers";

import styles from "../styles/Home.module.css";
import Navbar from "@/components/Navbar";
import { predictionWorld2Address } from "@/config";
import PredictionWorld from "../utils/PredictionWorld2.json";

export default function Portfolio() {
    const [portfolioValue, setPortfolioValue] = useState(0);

    const getMarkets = async () => {
        try {
            const { ethereum } = window;
            const provider = new ethers.providers.Web3Provider(ethereum);
            const signer = provider.getSigner();
            const predictionWorldContract = new ethers.Contract(
                predictionWorld2Address,
                PredictionWorld.abi,
                signer
            );

            let marketCount = await predictionWorldContract.totalMarkets();
            let markets = [];
            for (let i = 0; i < marketCount; i++) {
                let market = await predictionWorldContract.markets(i);
                
                console.log("*****");
                console.log(i);
                console.log(market.id);
                markets.push({
                    id: market.id
                });
            }

        } catch (error) {
            console.log(`Error getting amount, ${error}`);
        }
    }

    useEffect(() => {
        getMarkets();
    }, []);

    return (
        <div className={styles.container}>
            <Head>
                <title>Prediction World</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <main className="w-full flex flex-col sm:flex-row flex-wrap sm:flex-nowrap py-4 flex-grow max-w-5xl">
                <div className="w-full flex flex-col pt-1">
                    <div className="p-10 bg-blue-700 rounded-lg flex flex-row justify-evenly">
                        <div className="flex flex-col items-center">
                            <h1 className="text-white opacity-50 text-lg">Portfolio Value</h1>
                            <h1 className="text-white text-4xl font-bold">

                            </h1>
                        </div>
                    </div>
                </div>
            </main>
        </div>
    );
}