import dynamic from "next/dynamic";
import Head from "next/head";
import { Suspense } from "react";

/**
 * TODO:
 * 1. return back button
 * 2. add MUI style
 * 3. 個人資訊
 */

const BiconomyNavbar = dynamic(() => import("@/components/BiconomyNavbar").then((res) => res.default), {
    ssr: false
});

export const Header = () => {
    return (
        <>
            <Head>
                <title>Prediction World</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Suspense fallback={<div>Loading...</div>}>
                <BiconomyNavbar />
            </Suspense>
        </>
    );
};
